/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './api.module';
import * as import2 from '@angular/http';
class ApiModuleInjector extends import0.ɵNgModuleInjector<import1.ApiModule> {
  _HttpModule_0:import2.HttpModule;
  _ApiModule_1:import1.ApiModule;
  __BrowserXhr_2:import2.BrowserXhr;
  __ResponseOptions_3:import2.BaseResponseOptions;
  __XSRFStrategy_4:any;
  __XHRBackend_5:import2.XHRBackend;
  __RequestOptions_6:import2.BaseRequestOptions;
  __Http_7:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_2():import2.BrowserXhr {
    if ((this.__BrowserXhr_2 == null)) { (this.__BrowserXhr_2 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_2;
  }
  get _ResponseOptions_3():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_3 == null)) { (this.__ResponseOptions_3 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_3;
  }
  get _XSRFStrategy_4():any {
    if ((this.__XSRFStrategy_4 == null)) { (this.__XSRFStrategy_4 = import2.ɵb()); }
    return this.__XSRFStrategy_4;
  }
  get _XHRBackend_5():import2.XHRBackend {
    if ((this.__XHRBackend_5 == null)) { (this.__XHRBackend_5 = new import2.XHRBackend(this._BrowserXhr_2,this._ResponseOptions_3,this._XSRFStrategy_4)); }
    return this.__XHRBackend_5;
  }
  get _RequestOptions_6():import2.BaseRequestOptions {
    if ((this.__RequestOptions_6 == null)) { (this.__RequestOptions_6 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_6;
  }
  get _Http_7():any {
    if ((this.__Http_7 == null)) { (this.__Http_7 = import2.ɵc(this._XHRBackend_5,this._RequestOptions_6)); }
    return this.__Http_7;
  }
  createInternal():import1.ApiModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._ApiModule_1 = new import1.ApiModule();
    return this._ApiModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import1.ApiModule)) { return this._ApiModule_1; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_2; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_3; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_4; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_5; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_6; }
    if ((token === import2.Http)) { return this._Http_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ApiModuleNgFactory:import0.NgModuleFactory<import1.ApiModule> = new import0.NgModuleFactory<any>(ApiModuleInjector,import1.ApiModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhdmUvRGV2ZWxvcG1lbnQvR3l1bnUvbmctYXBpL3NyYy9hcGkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2RhdmUvRGV2ZWxvcG1lbnQvR3l1bnUvbmctYXBpL3NyYy9hcGkubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
